config/routes.rb
Rails.application.routes.draw do
  resources :verifications
  resources :watchdogs
  resources :users
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "user_log" => "watchdogs#user_log"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :watchdog , foreign_key: "admin_id"

  def self.setagent(useragentt)
    $useragenttx = useragentt.env['HTTP_USER_AGENT']
    $ip =   useragentt.remote_ip
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login , only: [:show, :edit, :update, :destroy,:index]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :get_two_factor ,only: [:show, :edit, :update,:index]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def homepage  
  
  end

  def unlockaccount
    @id = params[:id]
    @token = params[:token]
    @user = User.where("id =?",@id ).first
    @user.failedattempts = 0
    @user.disabled = 0
    @user.save
    flash.now.notice = 'Your account is Unlocked,please sign in .'
    render template: "sessions/new"
    

  end

  def confirmmail
    @id = params[:id]
    @token = params[:token]
    @user = User.where("id =?",@id ).first
    @verify_code = Verification.where("admin_id =?",@id ).first
    if @verify_code.email_confirmation_token == @token
      @user.update(:status => 1)
      @verify_code.update(:email_confirmed_at => Time.now)      
    end
    redirect_to @user
  end

  # GET /users/new
  def new
    @user = User.new
    render :layout => false
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.uuid = SecureRandom.hex(4)
    @token = SecureRandom.hex(4)
    respond_to do |format|
      if @user.save
        Verification.create(:admin_id => @user.id,:email_confirmation_token => @token)
        Watchdog.create(:admin_id => @user.id,:ipaddress => request.env['REMOTE_ADDR'],:logintime => Time.now,:lastvisit => Time.now )
        UserMailer.confirmmail(@user,@token).deliver_later
        format.html { redirect_to sign_in_path	, notice: 'User was successfully created,You should confirm your email before sign in' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  

  def get_two_factor
  end

  def post_two_factor
    @user_code = params[:confirm][:code]
    @sent_code = session[:token_code]
    session[:verify_code] = false
    if @user_code == @sent_code
      flash.now.notice = 'Welcome back!'
      session[:verify_code] = true

      redirect_to users_path
    else 
      flash.now.notice = 'wrong code!'
      redirect_to two_factor_path
    end
    
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:uuid, :roleid,  :firstname, :lastname, :language, :disabled, :loginattempts, :username, :email, :password)
      
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<br>

<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<br>


<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<br>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= form_for @user do |form| %>
<%= render partial: '/users/form', object: form %>
<%# render 'form', user: @user %>
<div class="submit-field">
<%= form.submit %>
</div>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/get_two_factor.html.erb
<!DOCTYPE html>
<!-- Template Name: Packet - Responsive Admin Template build with Twitter Bootstrap 3.x | Author: ClipTheme -->
<!--[if IE 8]><html class="ie8" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html lang="en">
	<!--<![endif]-->
	<!-- start: HEAD -->
	<head>
		<title>Payers - Payment Facilator</title>
		<!-- start: META -->
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<meta content="" name="description" />
		<meta content="" name="author" />
		<!-- end: META -->
		<!-- start: GOOGLE FONTS -->
		<link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
		<!-- end: GOOGLE FONTS -->
		<!-- start: MAIN CSS -->
		<link rel="stylesheet" href="../../bower_components/bootstrap/dist/css/bootstrap.min.css">
		<link rel="stylesheet" href="../../bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css">
		<link rel="stylesheet" href="../../bower_components/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="../../bower_components/themify-icons/themify-icons.css">
		<link rel="stylesheet" href="../../bower_components/flag-icon-css/css/flag-icon.min.css">
		<link rel="stylesheet" href="../../bower_components/animate.css/animate.min.css">
		<link rel="stylesheet" href="../../bower_components/perfect-scrollbar/css/perfect-scrollbar.min.css">
		<link rel="stylesheet" href="../../bower_components/switchery/dist/switchery.min.css">
		<link rel="stylesheet" href="../../bower_components/seiyria-bootstrap-slider/dist/css/bootstrap-slider.min.css">
		<link rel="stylesheet" href="../../bower_components/ladda/dist/ladda-themeless.min.css">
		<link rel="stylesheet" href="../../bower_components/slick.js/slick/slick.css">
		<link rel="stylesheet" href="../../bower_components/slick.js/slick/slick-theme.css">
		<!-- end: MAIN CSS -->
		<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
		<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
		<!-- start: Packet CSS -->
		<link rel="stylesheet" href="assets/css/styles.css">
		<link rel="stylesheet" href="assets/css/plugins.css">
		<link rel="stylesheet" href="assets/css/rtl.css">
		<link rel="stylesheet" href="assets/css/themes/lyt1-theme-1.css" id="skin_color">
		<!-- end: Packet CSS -->
		<!-- Favicon -->
		<link rel="shortcut icon" href="favicon.ico" />
	</head>
	<!-- end: HEAD -->
	<!-- start: BODY -->
	<body class="login">
		<!-- start: LOCK SCREEN -->
		<div class="row">
			<div class="lock-screen">
				<div class="box-ls">
					<img alt="" src="assets/images/logo-s.png" class="img-rounded" />
					<div class="user-info">
						<h4>Peter Clark</h4>
						<span>peter@example.com</span>
						<%= form_for :confirm , :url => two_factor_path do |f| %>
                            <div class="input-group">
                                <div class="form-group">
                                       <%= f.text_field :code , class: 'form-control' , placeholder: "Code to unlock" %>
                                </div>
								
								<span class="input-group-btn">
									<button class="btn btn-red" type="submit">
										<i class="fa fa-chevron-right"></i>
									</button> </span>
							</div>
                        <% end %>
                        <div class="text-center">
                        <%= link_to t(".forgot_password"),  sign_out_path, method: :delete %>
                    </div>
					</div>
				</div>
			</div>
        </div>
       
        
		<!-- end: LOCK SCREEN -->
		<!-- start: MAIN JAVASCRIPTS -->
		<script src="../../bower_components/jquery/dist/jquery.min.js"></script>
		<script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
		<script src="../../bower_components/components-modernizr/modernizr.js"></script>
		<script src="../../bower_components/js-cookie/src/js.cookie.js"></script>
		<script src="../../bower_components/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js"></script>
		<script src="../../bower_components/jquery-fullscreen/jquery.fullscreen-min.js"></script>
		<script src="../../bower_components/switchery/dist/switchery.min.js"></script>
		<script src="../../bower_components/jquery.knobe/dist/jquery.knob.min.js"></script>
		<script src="../../bower_components/seiyria-bootstrap-slider/dist/bootstrap-slider.min.js"></script>
		<script src="../../bower_components/slick.js/slick/slick.min.js"></script>
		<script src="../../bower_components/jquery-numerator/jquery-numerator.js"></script>
		<script src="../../bower_components/ladda/dist/spin.min.js"></script>
		<script src="../../bower_components/ladda/dist/ladda.min.js"></script>
		<script src="../../bower_components/ladda/dist/ladda.jquery.min.js"></script>
		<!-- end: MAIN JAVASCRIPTS -->
		<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<script src="../../bower_components/ckeditor/ckeditor.js"></script>
		<script src="../../bower_components/ckeditor/adapters/jquery.js"></script>
		<script src="../../bower_components/bb-jquery-validation/dist/jquery.validate.js"></script>
		<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<!-- start: Packet JAVASCRIPTS -->
		<script src="assets/js/letter-icons.js"></script>
		<script src="assets/js/main.js"></script>
		<!-- end: Packet JAVASCRIPTS -->
		<!-- start: JavaScript Event Handlers for this page -->
		<script src="assets/js/login.js"></script>
		<script>
			jQuery(document).ready(function() {
				Main.init();
				Login.init();
			});
		</script>
		<!-- end: JavaScript Event Handlers for this page -->
	</body>
</html>

app/views/users/homepage.html.erb
<br>
<%= link_to 'New User', new_user_path %>
<br>
<h1>Welcome To my project</h1>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<!DOCTYPE html>
<!-- Template Name: Packet - Responsive Admin Template build with Twitter Bootstrap 3.x | Author: ClipTheme -->
<!--[if IE 8]><html class="ie8" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html lang="en">
	<!--<![endif]-->
	<!-- start: HEAD -->
	<head>
		<title>Payers - Payment Facilator</title>
		<!-- start: META -->
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<meta content="" name="description" />
		<meta content="" name="author" />
		<!-- end: META -->
		<!-- start: GOOGLE FONTS -->
		<link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
		<!-- end: GOOGLE FONTS -->
		<!-- start: MAIN CSS -->
		<link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
		<link rel="stylesheet" href="/bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css">
		<link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="/bower_components/themify-icons/themify-icons.css">
		<link rel="stylesheet" href="/bower_components/flag-icon-css/css/flag-icon.min.css">
		<link rel="stylesheet" href="/bower_components/animate.css/animate.min.css">
		<link rel="stylesheet" href="/bower_components/perfect-scrollbar/css/perfect-scrollbar.min.css">
		<link rel="stylesheet" href="/bower_components/switchery/dist/switchery.min.css">
		<link rel="stylesheet" href="/bower_components/seiyria-bootstrap-slider/dist/css/bootstrap-slider.min.css">
		<link rel="stylesheet" href="/bower_components/ladda/dist/ladda-themeless.min.css">
		<link rel="stylesheet" href="/bower_components/slick.js/slick/slick.css">
		<link rel="stylesheet" href="/bower_components/slick.js/slick/slick-theme.css">
		<!-- end: MAIN CSS -->
		<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
		<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
		<!-- start: Packet CSS -->
		<link rel="stylesheet" href="/assets/css/styles.css">
		<link rel="stylesheet" href="/assets/css/plugins.css">
		<link rel="stylesheet" href="/assets/css/rtl.css">
		<link rel="stylesheet" href="/assets/css/themes/lyt1-theme-1.css" id="skin_color">
		<!-- end: Packet CSS -->
		<!-- Favicon -->
		<link rel="shortcut icon" href="favicon.ico" />
	</head>
	<!-- end: HEAD -->
	<!-- start: BODY -->
	<body class="login">
		<!-- start: REGISTRATION -->
    <div class="row">
    
      <%= form_for @user do |form| %>
			<div class="main-login col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4 col-lg-2 col-lg-offset-5">
				<div class="logo text-center">
					<img src="/assets/images/logo-s.png" alt="{{app.name}}" class="img-responsive" />
				</div>
				<p class="text-center text-dark text-bold text-extra-large margin-top-15">
					Sign Up
        </p>
        <%= csrf_meta_tag %>

        <p class="text-center">
					Enter your personal details below:
				</p>
				<!-- start: REGISTER BOX -->
				<div class="box-register">
					<form class="form-register">
            <div class="form-group">
                <%= form.text_field :firstname , class: 'form-control' , placeholder: "first Name" %>
            </div>
						<div class="form-group">
                <%= form.text_field :lastname , class: 'form-control' , placeholder: "Last Name" %>
            </div>
						<p>

				<p class="text-center">
					Enter your personal details below:
				</p>
        <!-- start: REGISTER BOX -->

				<div class="box-register">
          <form class="form-register">
          <div class="form-group">
             <%= form.text_field :email, type: 'email' , class: 'form-control' , placeholder: "Email" %>
          </div>
          <div class="form-group">
             <%= form.text_field :username , class: 'form-control' , placeholder: "User Name" %>
          </div>
          <div class="form-group">
             <%= form.password_field :password , class: 'form-control' , placeholder: "Password" %>
          </div>


						
						
						
						<div class="form-group">
							<div class="checkbox clip-check check-primary">
								<input type="checkbox" id="agree" name="agree" value="agree">
								<label for="agree"> I agree </label>
							</div>
						</div>
						<div class="form-actions">
							<p class="text-center">
								Already have an account?
								<%= link_to t(".sign_in"), sign_in_path %>
								
              </p>
              
			  <button type="submit" class="btn btn-red btn-block">
			         Submit
		      </button>

            </div>
           
						<hr />
						<p class="margin-top-10 text-center">
							Or sign up with a social network
						</p>
						<div class="social-icons text-center">
							<ul>
								<li class="social-twitter" uib-tooltip="Twitter" tooltip-placement="top">
									<a target="_blank" href="#"> Twitter </a>
								</li>
								<li class="social-google" uib-tooltip="Google" tooltip-placement="top">
									<a target="_blank" href="#"> Google </a>
								</li>
								<li class="social-facebook" uib-tooltip="Facebook" tooltip-placement="top">
									<a target="_blank" href="#"> Facebook </a>
								</li>
							</ul>
						</div>
					</form>
					<!-- start: COPYRIGHT -->
					<div class="copyright">
						2016 &copy; Packet by ClipTheme.
					</div>
					<!-- end: COPYRIGHT -->
				</div>
				<!-- end: REGISTER BOX -->
      </div>
      <% end %>
		</div>
		<!-- end: REGISTRATION -->
		<!-- start: MAIN JAVASCRIPTS -->
		<script src="/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
		<script src="/bower_components/components-modernizr/modernizr.js"></script>
		<script src="/bower_components/js-cookie/src/js.cookie.js"></script>
		<script src="/bower_components/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js"></script>
		<script src="/bower_components/jquery-fullscreen/jquery.fullscreen-min.js"></script>
		<script src="/bower_components/switchery/dist/switchery.min.js"></script>
		<script src="/bower_components/jquery.knobe/dist/jquery.knob.min.js"></script>
		<script src="/bower_components/seiyria-bootstrap-slider/dist/bootstrap-slider.min.js"></script>
		<script src="/bower_components/slick.js/slick/slick.min.js"></script>
		<script src="/bower_components/jquery-numerator/jquery-numerator.js"></script>
		<script src="/bower_components/ladda/dist/spin.min.js"></script>
		<script src="/bower_components/ladda/dist/ladda.min.js"></script>
		<script src="/bower_components/ladda/dist/ladda.jquery.min.js"></script>
		<!-- end: MAIN JAVASCRIPTS -->
		<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<script src="/bower_components/ckeditor/ckeditor.js"></script>
		<script src="/bower_components/ckeditor/adapters/jquery.js"></script>
		<script src="/bower_components/bb-jquery-validation/dist/jquery.validate.js"></script>
		<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<!-- start: Packet JAVASCRIPTS -->
		<script src="/assets/js/letter-icons.js"></script>
		<script src="/assets/js/main.js"></script>
		<!-- end: Packet JAVASCRIPTS -->
		<!-- start: JavaScript Event Handlers for this page -->
		<script src="/assets/js/login.js"></script>
		<script>
			jQuery(document).ready(function() {
			//	Main.init();
				//Login.init();
			});
		</script>
		<!-- end: JavaScript Event Handlers for this page -->
	</body>
</html>

app/views/users/post_two_factor.html.erb
<%= debug @user_code%>
<%= debug @sent_code %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>
<%= link_to t('show user log').html_safe, { :controller => :watchdogs,:action=>:user_log,:id => @user.id} %>
<br>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>