config/routes.rb
Rails.application.routes.draw do
  resources :verifications
  resources :watchdogs
  resources :users
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "user_log" => "watchdogs#user_log"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/watchdog.rb
class Watchdog < ApplicationRecord
    belongs_to :user ,:foreign_key => "admin_id"

end

app/controllers/watchdogs_controller.rb
class WatchdogsController < ApplicationController
  before_action :require_login , only: [:show, :edit, :update, :destroy,:index]
  before_action :set_watchdog, only: [:show, :edit, :update, :destroy]

  # GET /watchdogs
  # GET /watchdogs.json
  def index
    @watchdogs = Watchdog.all
  end

  # GET /watchdogs/1
  # GET /watchdogs/1.json
  def show
  end

  def user_log
    @log = Watchdog.where("admin_id =? ",params[:id]).joins("INNER JOIN users ON users.id = watchdogs.admin_id").distinct.all.order('created_at DESC')
 
  end

  # GET /watchdogs/new
  def new
    @watchdog = Watchdog.new
  end

  # GET /watchdogs/1/edit
  def edit
  end

  # POST /watchdogs
  # POST /watchdogs.json
  def create
    @watchdog = Watchdog.new(watchdog_params)

    respond_to do |format|
      if @watchdog.save
        format.html { redirect_to @watchdog, notice: 'Watchdog was successfully created.' }
        format.json { render :show, status: :created, location: @watchdog }
      else
        format.html { render :new }
        format.json { render json: @watchdog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watchdogs/1
  # PATCH/PUT /watchdogs/1.json
  def update
    respond_to do |format|
      if @watchdog.update(watchdog_params)
        format.html { redirect_to @watchdog, notice: 'Watchdog was successfully updated.' }
        format.json { render :show, status: :ok, location: @watchdog }
      else
        format.html { render :edit }
        format.json { render json: @watchdog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watchdogs/1
  # DELETE /watchdogs/1.json
  def destroy
    @watchdog.destroy
    respond_to do |format|
      format.html { redirect_to watchdogs_url, notice: 'Watchdog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watchdog
      @watchdog = Watchdog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def watchdog_params
      params.require(:watchdog).permit(:admin_id, :logintime, :ipaddress, :lastvisit)
    end
end

app/helpers/watchdogs_helper.rb
module WatchdogsHelper
end

app/views/watchdogs/_form.html.erb
<%= form_with(model: watchdog, local: true) do |form| %>
  <% if watchdog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(watchdog.errors.count, "error") %> prohibited this watchdog from being saved:</h2>

      <ul>
      <% watchdog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :admin_id %>
    <%= form.number_field :admin_id %>
  </div>

  <div class="field">
    <%= form.label :logintime %>
    <%= form.datetime_select :logintime %>
  </div>

  <div class="field">
    <%= form.label :ipaddress %>
    <%= form.text_area :ipaddress %>
  </div>

  <div class="field">
    <%= form.label :lastvisit %>
    <%= form.datetime_select :lastvisit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/watchdogs/edit.html.erb
<h1>Editing Watchdog</h1>

<%= render 'form', watchdog: @watchdog %>

<%= link_to 'Show', @watchdog %> |
<%= link_to 'Back', watchdogs_path %>

app/views/watchdogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Watchdogs</h1>

<table>
  <thead>
    <tr>
      <th>Admin</th>
      <th>Logintime</th>
      <th>Ipaddress</th>
      <th>Lastvisit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @watchdogs.each do |watchdog| %>
      <tr>
        <td><%= watchdog.admin_id %></td>
        <td><%= watchdog.logintime %></td>
        <td><%= watchdog.ipaddress %></td>
        <td><%= watchdog.lastvisit %></td>
        <td><%= link_to 'Show', watchdog %></td>
        <td><%= link_to 'Edit', edit_watchdog_path(watchdog) %></td>
        <td><%= link_to 'Destroy', watchdog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Watchdog', new_watchdog_path %>

app/views/watchdogs/new.html.erb
<h1>New Watchdog</h1>

<%= render 'form', watchdog: @watchdog %>

<%= link_to 'Back', watchdogs_path %>

app/views/watchdogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin:</strong>
  <%= @watchdog.admin_id %>
</p>

<p>
  <strong>Logintime:</strong>
  <%= @watchdog.logintime %>
</p>

<p>
  <strong>Ipaddress:</strong>
  <%= @watchdog.ipaddress %>
</p>

<p>
  <strong>Lastvisit:</strong>
  <%= @watchdog.lastvisit %>
</p>

<%= link_to 'Edit', edit_watchdog_path(@watchdog) %> |
<%= link_to 'Back', watchdogs_path %>

app/views/watchdogs/user_log.html.erb
<p id="notice"><%= notice %></p>

<h1>Watchdogs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Ip</th>
      <th>created_at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @log.each do |watchdog| %>
      <tr>
        <td><%= watchdog.user.username%></td>
        <td><%= watchdog.ipaddress %></td>
        <td><%= watchdog.created_at %></td>
        <td><%= link_to 'Show', watchdog %></td>
        <td><%= link_to 'Edit', edit_watchdog_path(watchdog) %></td>
        <td><%= link_to 'Destroy', watchdog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Watchdog', new_watchdog_path %>